entities/posts/model/GetLatestPosts.graphql, entities/posts/model/index.ts, entities/posts/model/index.tsx, entities/posts/ui/card/index.tsx, feature/front-page/model/GetFrontPage.graphql, feature/front-page/model/index.ts, package.json, pages/index.tsx, schema.graphql, shared/ui/grid/index.ts, yarn.lock
=> feat: main page grid layout

entities/posts/ui/article/index.tsx, shared/ui/share-button/index.tsx
Пока так, потом надо будет в иллюстраторе их обработать, чтобы убрать отступы внутри СВГ, и соответственно, выравнять их.
=> fix: position of share button

pages/_app.tsx
урлы то у некста, оказывается, чувствительны к регистру
=> fix: jetbrains mono fonts 404

codegen.yml, entities/posts/ui/article/index.tsx, entities/posts/ui/aside/index.tsx, pages/_app.tsx, pages/post/[uid].tsx, shared/api/index.ts, shared/api/types.ts
Зафиксировал шапку в приложении, добавил анимацию в приложение
=> feat: fixed header in app

entities/posts/ui/post-card/variants/center/index.tsx, entities/posts/ui/post-card/variants/center/styled.ts, entities/posts/ui/post-card/variants/default/index.tsx, features/front-page/ui/grid/index.tsx, pages/_app.tsx, shared/ui/grid/grid-area.tsx, shared/ui/index.ts, shared/ui/typography/index.ts, shared/ui/typography/types.ts
fix: исправить положение текста у CenterCard
refactor: переименовать GridAria -> GridArea
feat: стилизованный скроллбар
=> fix: исправить ширину шапки

src/shared/ui/image/index.tsx, src/shared/ui/markdown-renderer/index.tsx, yarn.lock
поправил отображение картинок в превью и в контентной части
=> preview images fixed

.env, src/entities/posts/ui/post-reader/ui/header/styled.ts
=> fix: mobile tags and share

.env, src/entities/posts/ui/post-card/variants/default/index.tsx, src/entities/posts/ui/post-card/variants/default/styled.ts, src/features/front-page/ui/grid/index.tsx, src/shared/api/types.ts, src/shared/ui/date-ago/index.tsx, src/shared/ui/date-ago/types.ts
=> fix: 671px post-card

src/entities/posts/ui/post-reader/ui/header/styled.ts
Изменил letter-spacing у дескрипшен и тайтл
=> fix: added letter spacing from escription and title

src/shared/ui/markdown-renderer/index.tsx
Изменил стиль шрифта у маркдауна
=> fix: changed font-style from markdown

src/entities/posts/ui/post-card/variants/center/index.tsx, src/entities/posts/ui/post-reader/ui/header/styled.ts, src/shared/ui/date-ago/index.tsx, src/shared/ui/date-ago/styles.ts, src/shared/ui/markdown-renderer/index.tsx, src/shared/ui/typography/index.ts, src/shared/ui/typography/types.ts, yarn.lock
- fix: date-fns method changed
- fix: mobile version title description size
- - ![image](https://user-images.githubusercontent.com/37376939/164968765-bf1710dd-6bcb-464c-87f8-2dcec22a7f2a.png)
- - ![image](https://user-images.githubusercontent.com/37376939/164968788-53439f54-c4f9-424f-bd66-e13f5ad20717.png)
- - ![image](https://user-images.githubusercontent.com/37376939/164968829-da7fbfd2-362c-4b4f-966b-192789b9a93d.png)
=> draft: feat: markdown renderer updates

components/packages/comments/__stories__/comments.stories.tsx, components/packages/comments/package.json, components/packages/comments/src/index.tsx, components/packages/comments/src/styled.ts, components/packages/comments/src/types.ts
=> feat: компонент комментария

next.config.js, src/widgets/header/ui/header/index.tsx
=> RAZ: fix bugs

src/shared/ui/footer/index.tsx, src/shared/ui/footer/styled.ts
=> alkov-footer-layout

package.json, src/entities/posts/ui/post-reader/ui/header/styled.ts, src/shared/ui/markdown-renderer/index.tsx
=> alkov: width from markdown and title

components/packages/clock/__stories__/clock.stories.tsx, components/packages/clock/package.json, components/packages/clock/src/index.tsx, schema.graphql, src/entities/clock/index.ts, src/entities/clock/model/GetCurrentTime.gql, src/entities/clock/model/index.ts, src/pages/_app.tsx, src/shared/api/types.ts, src/widgets/header/ui/header/index.tsx
=> feat: clock

src/widgets/comments/ui/hooks.ts, src/widgets/comments/ui/index.tsx, src/widgets/comments/ui/styled.ts
=> RAZ-142: fix order comments

src/shared/ui/footer/index.tsx
added links to the service links
=> added links to the service posts

src/shared/lib/helmet/index.tsx
Спасибо #298 за информацию про `twitter:site`.
Closes: #297
=> fix: Неправильный URL в meta тегах на странице публикации

package.json, src/entities/user-content/ui/user-info/index.tsx, src/shared/lib/parse-date/index.ts, yarn.lock
=> fix: проблема с таймзонами

README.md
=> Улучшил README, записал информацию, по некоторым проблемам из issues по запуску

components/packages/post-author/src/index.tsx, components/packages/typography/src/types.ts, src/entities/posts/ui/post-reader/ui/header/index.tsx, src/pages/post/[uid].tsx, src/shared/ui/date-ago/index.tsx, src/widgets/header/ui/preferences/index.tsx
И добавил отображение инициалов, вместо первых двух букв имени.
=> Добавил микроразметку Schema.org

components/packages/comments/src/hooks.ts, components/packages/comments/src/index.tsx, components/packages/comments/src/styled.ts, components/packages/comments/src/types.ts, src/shared/lib/helmet/index.tsx, src/widgets/comments/ui/index.tsx
closes #308 
https://user-images.githubusercontent.com/28918530/182706384-ae141b76-2145-487f-be99-a63fe00438e3.mp4
=> feat: Добавил подсветку реплая при переходе к нему и анимировал ховер комментариев

components/packages/clock/src/index.tsx, components/packages/posts/src/outline-card/layout/styled.ts, src/entities/layout/index.tsx, src/features/auth/ui/index.tsx, src/features/feeds/ui/selector/styled.ts, src/shared/ui/modal-action/index.tsx, src/shared/ui/modal-action/types.ts, src/shared/ui/modal/index.tsx, src/widgets/comments/ui/discard-button/index.tsx, src/widgets/comments/ui/index.tsx, src/widgets/header/ui/preferences/styled.ts
Улучшил навигацию по нажатию на таб.
Заменил некоторые теги на более верные с точки зрения семантики.
Теперь модальные окна рендерятся только после открытия, из-за этого нет фокуса на скрытые элементы.
Добавил подсветку при фокусе на кнопку авторизации.
=> Improve semantic tags and tab navigation

src/widgets/comments/ui/index.tsx
Closes #245 
https://user-images.githubusercontent.com/28918530/183281190-1eb37788-93f5-44ce-9fe5-720654cfd84e.mov
=> Fix: Добавил подскролл к отправленному комменту 

components/.storybook/preview.jsx, components/package.json, components/packages/comments/src/styled.ts, components/packages/posts/src/card/layout/styled.ts, components/packages/posts/src/outline-card/layout/styled.ts, components/packages/responsive/__stories__/responsive.stories.tsx, components/packages/responsive/src/Media.ts, components/packages/responsive/src/hooks.ts, components/packages/responsive/src/index.tsx, components/packages/theme/src/common.ts, components/packages/theme/src/types.ts, src/entities/posts/ui/post-reader/ui/header/styled.ts, src/entities/posts/ui/post-reader/ui/styled.ts, src/features/feeds/ui/selector/styled.ts, src/features/front-page/ui/grid/index.tsx, src/features/front-page/ui/item/index.tsx, src/shared/ui/drawer/styled.ts, src/shared/ui/footer/styled.ts, src/shared/ui/grid/styled.ts, src/shared/ui/markdown-renderer/index.tsx, src/shared/ui/wrapper/styled.ts, src/widgets/comments/ui/input/styled.ts
Closes #244 
Чем больше людей посмотрит этот ПР, тем лучше. Глаз замыливается при просмотре)
test cases: 
```
1) Открыл на одной вкладке локалку, а на другой прод
2) Прошелся на страницах /, /feeds/[uid], /post/[uid] по каждому
3) Убедился, что критически ничего не изменилось 
```
Вместе с этими правками пофиксились баги, где не сходились медиа-запросы разных модулей. Например, в одном блоке было прописано `max-width: 620px`, а в соседнем `max-width: 619px` и на разрешении 620px все шло пиздой
=> feat: Добавил централизованную таблицу медиа-квери

src/entities/posts/ui/post-reader/ui/header/styled.ts, src/entities/user-content/ui/user-info/index.tsx
=> Fix: Небольшие фиксы разметки

components/packages/comments/src/styled.ts, components/packages/theme/src/dark/index.ts, components/packages/theme/src/light/index.ts, components/packages/theme/src/types.ts, src/pages/_app.tsx, src/pages/_document.tsx, src/shared/ui/body/index.ts, src/shared/ui/global-styles/index.ts, src/widgets/comments/ui/comments-wrapper/index.ts, src/widgets/comments/ui/input/styled.ts, src/widgets/comments/ui/input/utils.ts, src/widgets/comments/ui/reply-preview/index.tsx, src/widgets/comments/ui/reply-preview/styled.ts, src/widgets/comments/ui/styled.ts
=> Fix: Подпилил баги светлой темы

src/shared/ui/markdown-renderer/index.tsx, src/shared/ui/markdown-renderer/theme.ts
https://user-images.githubusercontent.com/37376939/184523731-3a1149b5-e801-43c0-8dbb-4d4200e503d2.mp4
=> feat: code blocks theme switching

src/features/feeds/ui/selector/styled.ts, src/shared/ui/footer/index.tsx, src/shared/ui/icon-button/index.tsx, src/widgets/comments/ui/comments-wrapper/index.ts, src/widgets/header/ui/preferences/styled.ts, src/widgets/header/ui/preferences/utils.ts
=> Fix: Несколько фиксов верстки

src/shared/ui/markdown-renderer/index.tsx, src/shared/ui/markdown-renderer/theme.ts
Closes #418 
**Light theme**:
**Dark theme**:
**Дополнительно**:
+ поменял некоторые цвета в соответствие с [дизайном](https://www.figma.com/file/NO0RmwhfZnsOjW1cexIVEW/%F0%9F%94%B8-rzrbs) 
@raantoniv @default-razrab  посмотрите плиз
=> feat: add code color theme

src/entities/posts/ui/post-reader/ui/aside/index.tsx, src/entities/posts/ui/post-reader/ui/aside/styled.ts, src/entities/posts/ui/post-reader/ui/aside/types.ts, src/entities/posts/ui/post-reader/ui/header/index.tsx, src/entities/posts/ui/post-reader/ui/header/styled.ts, src/entities/posts/ui/post-reader/ui/hooks.ts, src/entities/posts/ui/post-reader/ui/index.tsx, src/entities/posts/ui/post-reader/ui/styled.ts, src/shared/ui/share-button/lib/types.ts, src/shared/ui/share-button/lib/withCopyToClipboard.tsx, src/shared/ui/share-button/types.ts
Переверстал. Теперь Сайдбар отдельно от шапки.
Сайдбар прилипает, затеняется, появляется дополнительная информация
https://user-images.githubusercontent.com/17778661/185504277-77c687cc-aa42-44d2-9eb8-abc581c42792.mp4
Close #254
=> Sticky aside layout

src/shared/ui/modal-action/index.tsx, src/shared/ui/modal-action/styles.ts
=> issue-426: replace link tag with button

package.json, src/shared/lib/helmet/index.tsx, src/shared/ui/markdown-renderer/index.tsx, yarn.lock
=> Встраиваемые YouTube видео на странице публикации
